pub enum Language {
    English,
    Spanish,
    Portuguese,
    German,
    Dutch,
}

#[derive(Clone)]
pub struct Lang {
    pub title: &'static str,
    pub prompt_guess: &'static str,
    pub win_msg: &'static str,
    pub lose_msg: &'static str,
    pub press_enter: &'static str,
    pub word_label: &'static str,
    pub guessed_label: &'static str,
    pub attempts_label: &'static str,
    pub time_left_label: &'static str,
    pub error_not_letter: &'static str,
    pub error_already_guessed: &'static str,
    pub menu_game_selection: &'static str,
    pub menu_hangman: &'static str,
    pub menu_tictactoe: &'static str,
    pub menu_chess: &'static str,
    pub chess_title: &'static str,
    pub chess_your_turn: &'static str,
    pub chess_white_wins: &'static str,
    pub chess_black_wins: &'static str,
    pub chess_stalemate: &'static str,
    pub chess_draw: &'static str,
    pub chess_instructions_ongoing: &'static str,
    pub chess_instructions_over: &'static str,
    pub menu_pong: &'static str,
    pub menu_matrix: &'static str,
    pub menu_paradox: &'static str,
    pub menu_recommender: &'static str,
    pub paradox_title: &'static str,
    pub paradox_stage: &'static str,
    pub paradox_bypass_hint: &'static str,
    pub paradox_bypass_msg: &'static str,
    pub paradox_complete: &'static str,
    pub paradox_complete_msg: &'static str,
    pub paradox_esc: &'static str,
    pub paradox_s1_title: &'static str,
    pub paradox_s1_desc: &'static str,
    pub paradox_s1_freeze: &'static str,
    pub paradox_s1_hint: &'static str,
    pub paradox_s2_title: &'static str,
    pub paradox_s2_desc: &'static str,
    pub paradox_s2_alpha: &'static str,
    pub paradox_s2_beta: &'static str,
    pub paradox_s2_opt0: &'static str,
    pub paradox_s2_opt1: &'static str,
    pub paradox_s2_opt2: &'static str,
    pub paradox_s2_opt3: &'static str,
    pub paradox_s3_title: &'static str,
    pub paradox_s3_desc: &'static str,
    pub paradox_s3_hint: &'static str,
    pub paradox_s3_peak: &'static str,
    pub paradox_s3_miss: &'static str,
    pub paradox_s4_title: &'static str,
    pub paradox_s4_q0: &'static str,
    pub paradox_s4_q0_a0: &'static str,
    pub paradox_s4_q0_a1: &'static str,
    pub paradox_s4_q0_a2: &'static str,
    pub paradox_s4_q0_a3: &'static str,
    pub paradox_s4_q1: &'static str,
    pub paradox_s4_q1_a0: &'static str,
    pub paradox_s4_q1_a1: &'static str,
    pub paradox_s4_q1_a2: &'static str,
    pub paradox_s4_q1_a3: &'static str,
    pub paradox_s4_q2: &'static str,
    pub paradox_s4_q2_a0: &'static str,
    pub paradox_s4_q2_a1: &'static str,
    pub paradox_s4_q2_a2: &'static str,
    pub paradox_s4_q2_a3: &'static str,
    pub paradox_s5_title: &'static str,
    pub paradox_s5_desc: &'static str,
    pub paradox_s5_timer: &'static str,
    pub paradox_s5_round: &'static str,
    pub recommender_title: &'static str,
    pub recommender_subtitle: &'static str,
    pub recommender_menu_movies: &'static str,
    pub recommender_menu_series: &'static str,
    pub recommender_menu_manga: &'static str,
    pub recommender_menu_books: &'static str,
    pub recommender_menu_anime: &'static str,
    pub recommender_menu_cartoons: &'static str,
    pub recommender_menu_videogames: &'static str,
    pub recommender_menu_music: &'static str,
    pub music_menu_title: &'static str,
    pub music_menu_rock: &'static str,
    pub music_menu_hiphop: &'static str,
    pub music_menu_pop: &'static str,
    pub music_menu_electronic: &'static str,
    pub music_menu_classical: &'static str,
    pub music_menu_salsa: &'static str,
    pub music_menu_reggae: &'static str,
    pub music_go_back: &'static str,
    pub recommender_go_back: &'static str,
    pub series: &'static [&'static str],
    pub mangas: &'static [&'static str],
    pub books: &'static [&'static str],
    pub animes: &'static [&'static str],
    pub cartoons: &'static [&'static str],
    pub videogames: &'static [&'static str],
    pub music_rock: &'static [&'static str],
    pub music_hiphop: &'static [&'static str],
    pub music_pop: &'static [&'static str],
    pub music_electronic: &'static [&'static str],
    pub music_classical: &'static [&'static str],
    pub music_salsa: &'static [&'static str],
    pub music_reggae: &'static [&'static str],
    pub pong_title: &'static str,
    pub pong_player_wins: &'static str,
    pub pong_computer_wins: &'static str,
    pub pong_instructions: &'static str,
    pub menu_go_back: &'static str,
    pub movies: &'static [&'static str],
}

impl Lang {
    pub fn english() -> Self {
        Lang {
            title: "HANGMAN",
            prompt_guess: "Enter a letter (or 'ESC' to exit): ",
            win_msg: "Congratulations! You won!",
            lose_msg: "Game over! The word was: ",
            press_enter: "Press Enter to continue...",
            word_label: "Word: ",
            guessed_label: "Guessed letters: ",
            attempts_label: "Attempts left: ",
            time_left_label: "Time left: ",
            error_not_letter: "Please enter a letter",
            error_already_guessed: "You already guessed that letter",
            menu_game_selection: "Game Selection",
            menu_hangman: "1. Hangman",
            menu_tictactoe: "2. Tic-Tac-Toe",
            menu_chess: "3. Chess",
            chess_title: "CHESS",
            chess_your_turn: "Your turn",
            chess_white_wins: "White wins!",
            chess_black_wins: "Black wins!",
            chess_stalemate: "Stalemate!",
            chess_draw: "Draw!",
            chess_instructions_ongoing: "Arrow keys to move, Enter to select/move. ESC to go back.",
            chess_instructions_over: "Press Enter to play again. ESC to go back.",
            menu_pong: "4. Pong",
            menu_matrix: "5. Matrix",
            menu_paradox: "6. Paradox",
            menu_recommender: "6. Recommender",
            paradox_title: "PARADOX",
            paradox_stage: "Stage",
            paradox_bypass_hint: "[B] Logic Bypass",
            paradox_bypass_msg: "Reality.exe has stopped obeying. You hacked causality with a single keystroke.",
            paradox_complete: "PARADOX RESOLVED",
            paradox_complete_msg: "You bent logic until it snapped back into place. The universe reluctantly agrees.",
            paradox_esc: "ESC to return",
            paradox_s1_title: "The Teleporting Selector",
            paradox_s1_desc: "Catch the button during its lime freeze window. Outside it, the target teleports away.",
            paradox_s1_freeze: "FREEZE WINDOW ACTIVE",
            paradox_s1_hint: "Arrows move cursor. Enter selects. Wait for lime glow.",
            paradox_s2_title: "The Liar's Gate",
            paradox_s2_desc: "Two guards block the path. One always lies, one always tells the truth.",
            paradox_s2_alpha: "Alpha: \"Beta is the liar.\"",
            paradox_s2_beta: "Beta: \"We both lie.\"",
            paradox_s2_opt0: "Ask Alpha which door is safe",
            paradox_s2_opt1: "Ask Beta which door is safe",
            paradox_s2_opt2: "Trust the left door",
            paradox_s2_opt3: "Trust the right door",
            paradox_s3_title: "Schrödinger's Wave",
            paradox_s3_desc: "The cat is both alive and dead until you collapse the wave at its peak.",
            paradox_s3_hint: "Press SPACE exactly when the wave crests (█).",
            paradox_s3_peak: "Wave collapsed! Superposition resolved.",
            paradox_s3_miss: "Wrong phase. The cat is still in flux.",
            paradox_s4_title: "The Paradox Quiz",
            paradox_s4_q0: "How many questions are in this quiz?",
            paradox_s4_q0_a0: "Two",
            paradox_s4_q0_a1: "Four",
            paradox_s4_q0_a2: "Three",
            paradox_s4_q0_a3: "This statement is false",
            paradox_s4_q1: "The answer to this question is:",
            paradox_s4_q1_a0: "The previous answer",
            paradox_s4_q1_a1: "The next answer",
            paradox_s4_q1_a2: "Forty-two",
            paradox_s4_q1_a3: "All of the above",
            paradox_s4_q2: "If you answered correctly, pick the wrong option:",
            paradox_s4_q2_a0: "Definitely this one",
            paradox_s4_q2_a1: "Obviously this one",
            paradox_s4_q2_a2: "Certainly this one",
            paradox_s4_q2_a3: "None of these (correct)",
            paradox_s5_title: "The Reverse Turing Test",
            paradox_s5_desc: "Prove you are human. Solve before the timer expires.",
            paradox_s5_timer: "Time",
            paradox_s5_round: "Round",
            recommender_title: "RECOMMENDER",
            recommender_subtitle: "You should check out:",
            recommender_menu_movies: "1. Movies",
            recommender_menu_series: "2. Series",
            recommender_menu_manga: "3. Manga",
            recommender_menu_books: "4. Books",
            recommender_menu_anime: "5. Anime",
            recommender_menu_cartoons: "6. Cartoons",
            recommender_menu_videogames: "7. Video Games",
            recommender_menu_music: "8. Music",
            music_menu_title: "MUSIC GENRES",
            music_menu_rock: "1. Rock",
            music_menu_hiphop: "2. Hip-Hop",
            music_menu_pop: "3. Pop",
            music_menu_electronic: "4. Electronic",
            music_menu_classical: "5. Classical",
            music_menu_salsa: "6. Salsa",
            music_menu_reggae: "7. Reggae",
            music_go_back: "8. Go Back (ESC)",
            recommender_go_back: "A. Go Back (ESC)",
            series: super::wordlist::SERIES,
            mangas: super::wordlist::MANGA,
            books: super::wordlist::BOOKS,
            animes: super::wordlist::ANIME,
            cartoons: super::wordlist::CARTOONS,
            videogames: super::wordlist::VIDEO_GAMES,
            
            music_rock: super::wordlist::MUSIC_ROCK,
            music_hiphop: super::wordlist::MUSIC_HIPHOP,
            music_pop: super::wordlist::MUSIC_POP,
            music_electronic: super::wordlist::MUSIC_ELECTRONIC,
            music_classical: super::wordlist::MUSIC_CLASSICAL,
            music_salsa: super::wordlist::MUSIC_SALSA,
            music_reggae: super::wordlist::MUSIC_REGGAE,
            pong_title: "PONG",
            pong_player_wins: "Player wins!",
            pong_computer_wins: "Computer wins!",
            pong_instructions: "Up/Down to move. ESC to go back.",
            menu_go_back: "7. Go Back (ESC)",
            movies: super::wordlist::ENGLISH_MOVIES,
        }
    }

    pub fn spanish() -> Self {
        Lang {
            title: "AHORCADO",
            prompt_guess: "Ingresa una letra (o 'ESC' para salir): ",
            win_msg: "¡Felicidades! ¡Ganaste!",
            lose_msg: "¡Juego terminado! La palabra era: ",
            press_enter: "Presiona Enter para continuar...",
            word_label: "Palabra: ",
            guessed_label: "Letras adivinadas: ",
            attempts_label: "Intentos restantes: ",
            time_left_label: "Tiempo restante: ",
            error_not_letter: "Por favor ingresa una letra",
            error_already_guessed: "Ya adivinaste esa letra",
            menu_game_selection: "Selección de Juego",
            menu_hangman: "1. Ahorcado",
            menu_tictactoe: "2. Tres en Raya",
            menu_chess: "3. Ajedrez",
            chess_title: "AJEDREZ",
            chess_your_turn: "Tu turno",
            chess_white_wins: "¡Las blancas ganan!",
            chess_black_wins: "¡Las negras ganan!",
            chess_stalemate: "¡Rey ahogado!",
            chess_draw: "¡Empate!",
            chess_instructions_ongoing: "Flechas para mover, Enter para seleccionar/mover. ESC para volver.",
            chess_instructions_over: "Presiona Enter para jugar de nuevo. ESC para volver.",
            menu_pong: "4. Pong",
            menu_matrix: "5. Matrix",
            menu_paradox: "6. Paradox",
            menu_recommender: "6. Recomendador",
            paradox_title: "PARADOJA",
            paradox_stage: "Etapa",
            paradox_bypass_hint: "[B] Bypass Lógico",
            paradox_bypass_msg: "Reality.exe dejó de obedecer. Hackeaste la causalidad con una tecla.",
            paradox_complete: "PARADOJA RESUELTA",
            paradox_complete_msg: "Doblaste la lógica hasta que volvió a su sitio. El universo accede a regañadientes.",
            paradox_esc: "ESC para volver",
            paradox_s1_title: "El Selector Teletransportador",
            paradox_s1_desc: "Atrapa el botón durante su ventana de congelación lima. Fuera de ella, el objetivo se teletransporta.",
            paradox_s1_freeze: "VENTANA DE CONGELACIÓN ACTIVA",
            paradox_s1_hint: "Flechas mueven el cursor. Enter selecciona. Espera el brillo lima.",
            paradox_s2_title: "La Puerta del Mentiroso",
            paradox_s2_desc: "Dos guardias bloquean el camino. Uno siempre miente, el otro siempre dice la verdad.",
            paradox_s2_alpha: "Alfa: \"Beta es el mentiroso.\"",
            paradox_s2_beta: "Beta: \"Los dos mentimos.\"",
            paradox_s2_opt0: "Preguntar a Alfa qué puerta es segura",
            paradox_s2_opt1: "Preguntar a Beta qué puerta es segura",
            paradox_s2_opt2: "Confiar en la puerta izquierda",
            paradox_s2_opt3: "Confiar en la puerta derecha",
            paradox_s3_title: "La Onda de Schrödinger",
            paradox_s3_desc: "El gato está vivo y muerto hasta que colapses la onda en su pico.",
            paradox_s3_hint: "Presiona ESPACIO exactamente cuando la onda creste (█).",
            paradox_s3_peak: "¡Onda colapsada! Superposición resuelta.",
            paradox_s3_miss: "Fase incorrecta. El gato sigue en flujo.",
            paradox_s4_title: "El Quiz de la Paradoja",
            paradox_s4_q0: "¿Cuántas preguntas hay en este quiz?",
            paradox_s4_q0_a0: "Dos",
            paradox_s4_q0_a1: "Cuatro",
            paradox_s4_q0_a2: "Tres",
            paradox_s4_q0_a3: "Esta afirmación es falsa",
            paradox_s4_q1: "La respuesta a esta pregunta es:",
            paradox_s4_q1_a0: "La respuesta anterior",
            paradox_s4_q1_a1: "La siguiente respuesta",
            paradox_s4_q1_a2: "Cuarenta y dos",
            paradox_s4_q1_a3: "Todas las anteriores",
            paradox_s4_q2: "Si respondiste correctamente, elige la opción incorrecta:",
            paradox_s4_q2_a0: "Definitivamente esta",
            paradox_s4_q2_a1: "Obviamente esta",
            paradox_s4_q2_a2: "Ciertamente esta",
            paradox_s4_q2_a3: "Ninguna de estas (correcta)",
            paradox_s5_title: "El Test de Turing Inverso",
            paradox_s5_desc: "Demuestra que eres humano. Resuelve antes de que expire el temporizador.",
            paradox_s5_timer: "Tiempo",
            paradox_s5_round: "Ronda",
            recommender_title: "RECOMENDADOR",
            recommender_subtitle: "Deberías ver/leer:",
            recommender_menu_movies: "1. Películas",
            recommender_menu_series: "2. Series",
            recommender_menu_manga: "3. Manga",
            recommender_menu_books: "4. Libros",
            recommender_menu_anime: "5. Anime",
            recommender_menu_cartoons: "6. Dibujos Animados",
            recommender_menu_videogames: "7. Videojuegos",
            recommender_menu_music: "8. Música",
            music_menu_title: "GÉNEROS MUSICALES",
            music_menu_rock: "1. Rock",
            music_menu_hiphop: "2. Hip-Hop",
            music_menu_pop: "3. Pop",
            music_menu_electronic: "4. Electrónica",
            music_menu_classical: "5. Clásica",
            music_menu_salsa: "6. Salsa",
            music_menu_reggae: "7. Reggae",
            music_go_back: "8. Volver (ESC)",
            recommender_go_back: "A. Volver (ESC)",
            series: super::wordlist::SERIES,
            mangas: super::wordlist::MANGA,
            books: super::wordlist::BOOKS,
            animes: super::wordlist::ANIME,
            cartoons: super::wordlist::CARTOONS,
            videogames: super::wordlist::VIDEO_GAMES,
            
            music_rock: super::wordlist::MUSIC_ROCK,
            music_hiphop: super::wordlist::MUSIC_HIPHOP,
            music_pop: super::wordlist::MUSIC_POP,
            music_electronic: super::wordlist::MUSIC_ELECTRONIC,
            music_classical: super::wordlist::MUSIC_CLASSICAL,
            music_salsa: super::wordlist::MUSIC_SALSA,
            music_reggae: super::wordlist::MUSIC_REGGAE,
            pong_title: "PONG",
            pong_player_wins: "¡El jugador gana!",
            pong_computer_wins: "¡La computadora gana!",
            pong_instructions: "Arriba/Abajo para mover. ESC para volver.",
            menu_go_back: "7. Volver (ESC)",
            movies: super::wordlist::SPANISH_MOVIES,
        }
    }

    pub fn portuguese() -> Self {
        Lang {
            title: "FORCA",
            prompt_guess: "Digita uma letra (ou 'ESC' para sair): ",
            win_msg: "Parabéns! Ganhaste!",
            lose_msg: "Fim de jogo! A palavra era: ",
            press_enter: "Pressione Enter para continuar...",
            word_label: "Palavra: ",
            guessed_label: "Letras adivinhadas: ",
            attempts_label: "Tentativas restantes: ",
            time_left_label: "Tempo restante: ",
            error_not_letter: "Por favor, digita uma letra",
            error_already_guessed: "Já adivinhaste esta letra",
            menu_game_selection: "Seleção de Jogo",
            menu_hangman: "1. Forca",
            menu_tictactoe: "2. Jogo do Galo",
            menu_chess: "3. Xadrez",
            chess_title: "XADREZ",
            chess_your_turn: "A tua vez",
            chess_white_wins: "As brancas vencem!",
            chess_black_wins: "As pretas vencem!",
            chess_stalemate: "Afogamento!",
            chess_draw: "Empate!",
            chess_instructions_ongoing: "Setas para mover, Enter para selecionar/mover. ESC para voltar.",
            chess_instructions_over: "Pressione Enter para jogar novamente. ESC para voltar.",
            menu_pong: "4. Pong",
            menu_matrix: "5. Matrix",
            menu_paradox: "6. Paradox",
            menu_recommender: "6. Recomendador",
            paradox_title: "PARADOXO",
            paradox_stage: "Fase",
            paradox_bypass_hint: "[B] Bypass Lógico",
            paradox_bypass_msg: "Reality.exe parou de obedecer. Hackeaste a causalidade com uma tecla.",
            paradox_complete: "PARADOXO RESOLVIDO",
            paradox_complete_msg: "Dobraste a lógica até ela voltar ao lugar. O universo concorda a contragosto.",
            paradox_esc: "ESC para voltar",
            paradox_s1_title: "O Seletor Teletransportador",
            paradox_s1_desc: "Apanha o botão durante a janela de congelamento lima. Fora dela, o alvo teletransporta-se.",
            paradox_s1_freeze: "JANELA DE CONGELAMENTO ATIVA",
            paradox_s1_hint: "Setas movem o cursor. Enter seleciona. Espera pelo brilho lima.",
            paradox_s2_title: "O Portão do Mentiroso",
            paradox_s2_desc: "Dois guardas bloqueiam o caminho. Um sempre mente, o outro sempre diz a verdade.",
            paradox_s2_alpha: "Alfa: \"Beta é o mentiroso.\"",
            paradox_s2_beta: "Beta: \"Ambos mentimos.\"",
            paradox_s2_opt0: "Perguntar a Alfa qual porta é segura",
            paradox_s2_opt1: "Perguntar a Beta qual porta é segura",
            paradox_s2_opt2: "Confiar na porta esquerda",
            paradox_s2_opt3: "Confiar na porta direita",
            paradox_s3_title: "A Onda de Schrödinger",
            paradox_s3_desc: "O gato está vivo e morto até colapsares a onda no seu pico.",
            paradox_s3_hint: "Pressiona ESPAÇO exatamente quando a onda atinge o cume (█).",
            paradox_s3_peak: "Onda colapsada! Superposição resolvida.",
            paradox_s3_miss: "Fase errada. O gato ainda está em fluxo.",
            paradox_s4_title: "O Quiz do Paradoxo",
            paradox_s4_q0: "Quantas perguntas há neste quiz?",
            paradox_s4_q0_a0: "Duas",
            paradox_s4_q0_a1: "Quatro",
            paradox_s4_q0_a2: "Três",
            paradox_s4_q0_a3: "Esta afirmação é falsa",
            paradox_s4_q1: "A resposta a esta pergunta é:",
            paradox_s4_q1_a0: "A resposta anterior",
            paradox_s4_q1_a1: "A próxima resposta",
            paradox_s4_q1_a2: "Quarenta e dois",
            paradox_s4_q1_a3: "Todas as anteriores",
            paradox_s4_q2: "Se respondeste corretamente, escolhe a opção errada:",
            paradox_s4_q2_a0: "Definitivamente esta",
            paradox_s4_q2_a1: "Obviamente esta",
            paradox_s4_q2_a2: "Certamente esta",
            paradox_s4_q2_a3: "Nenhuma destas (correta)",
            paradox_s5_title: "O Teste de Turing Reverso",
            paradox_s5_desc: "Prova que és humano. Resolve antes do temporizador expirar.",
            paradox_s5_timer: "Tempo",
            paradox_s5_round: "Ronda",
            recommender_title: "RECOMENDADOR",
            recommender_subtitle: "Você deveria conferir:",
            recommender_menu_movies: "1. Filmes",
            recommender_menu_series: "2. Séries",
            recommender_menu_manga: "3. Mangá",
            recommender_menu_books: "4. Livros",
            recommender_menu_anime: "5. Anime",
            recommender_menu_cartoons: "6. Desenhos Animados",
            recommender_menu_videogames: "7. Videogames",
            recommender_menu_music: "8. Música",
            music_menu_title: "GÊNEROS MUSICAIS",
            music_menu_rock: "1. Rock",
            music_menu_hiphop: "2. Hip-Hop",
            music_menu_pop: "3. Pop",
            music_menu_electronic: "4. Eletrônica",
            music_menu_classical: "5. Clássica",
            music_menu_salsa: "6. Salsa",
            music_menu_reggae: "7. Reggae",
            music_go_back: "8. Voltar (ESC)",
            recommender_go_back: "A. Voltar (ESC)",
            series: super::wordlist::SERIES,
            mangas: super::wordlist::MANGA,
            books: super::wordlist::BOOKS,
            animes: super::wordlist::ANIME,
            cartoons: super::wordlist::CARTOONS,
            videogames: super::wordlist::VIDEO_GAMES,
            
            music_rock: super::wordlist::MUSIC_ROCK,
            music_hiphop: super::wordlist::MUSIC_HIPHOP,
            music_pop: super::wordlist::MUSIC_POP,
            music_electronic: super::wordlist::MUSIC_ELECTRONIC,
            music_classical: super::wordlist::MUSIC_CLASSICAL,
            music_salsa: super::wordlist::MUSIC_SALSA,
            music_reggae: super::wordlist::MUSIC_REGGAE,
            pong_title: "PONG",
            pong_player_wins: "O jogador vence!",
            pong_computer_wins: "O computador vence!",
            pong_instructions: "Cima/Baixo para mover. ESC para voltar.",
            menu_go_back: "7. Voltar (ESC)",
            movies: super::wordlist::PORTUGUESE_MOVIES,
        }
    }

    pub fn german() -> Self {
        Lang {
            title: "GALGENMÄNNCHEN",
            prompt_guess: "Buchstabe eingeben (oder 'ESC' zum Beenden): ",
            win_msg: "Herzlichen Glückwunsch! Du hast gewonnen!",
            lose_msg: "Spiel vorbei! Das Wort war: ",
            press_enter: "Drücke Enter, um fortzufahren...",
            word_label: "Wort: ",
            guessed_label: "Geratene Buchstaben: ",
            attempts_label: "Verbleibende Versuche: ",
            time_left_label: "Verbleibende Zeit: ",
            error_not_letter: "Bitte gib einen Buchstaben ein",
            error_already_guessed: "Du hast diesen Buchstaben bereits geraten",
            menu_game_selection: "Spielauswahl",
            menu_hangman: "1. Galgenmännchen",
            menu_tictactoe: "2. Tic-Tac-Toe",
            menu_chess: "3. Schach",
            chess_title: "SCHACH",
            chess_your_turn: "Du bist dran",
            chess_white_wins: "Weiß gewinnt!",
            chess_black_wins: "Schwarz gewinnt!",
            chess_stalemate: "Patt!",
            chess_draw: "Unentschieden!",
            chess_instructions_ongoing: "Pfeiltasten zum Bewegen, Enter zum Auswählen/Ziehen. ESC zurück.",
            chess_instructions_over: "Enter drücken für ein neues Spiel. ESC zum Zurückgehen.",
            menu_pong: "4. Pong",
            menu_matrix: "5. Matrix",
            menu_paradox: "6. Paradox",
            menu_recommender: "6. Empfehlungen",
            paradox_title: "PARADOX",
            paradox_stage: "Stufe",
            paradox_bypass_hint: "[B] Logik-Bypass",
            paradox_bypass_msg: "Reality.exe gehorcht nicht mehr. Du hast die Kausalität mit einer Taste gehackt.",
            paradox_complete: "PARADOX GELÖST",
            paradox_complete_msg: "Du hast die Logik gebogen, bis sie zurücksprang. Das Universum stimmt widerwillig zu.",
            paradox_esc: "ESC zum Zurückkehren",
            paradox_s1_title: "Der Teleportierende Selektor",
            paradox_s1_desc: "Fange den Knopf während des limafarbenen Freeze-Fensters. Sonst teleportiert er weg.",
            paradox_s1_freeze: "FREEZE-FENSTER AKTIV",
            paradox_s1_hint: "Pfeiltasten bewegen den Cursor. Enter wählt. Warte auf das Limaleuchten.",
            paradox_s2_title: "Das Tor des Lügners",
            paradox_s2_desc: "Zwei Wächter blockieren den Weg. Einer lügt immer, der andere sagt immer die Wahrheit.",
            paradox_s2_alpha: "Alpha: \"Beta ist der Lügner.\"",
            paradox_s2_beta: "Beta: \"Wir lügen beide.\"",
            paradox_s2_opt0: "Alpha fragen, welche Tür sicher ist",
            paradox_s2_opt1: "Beta fragen, welche Tür sicher ist",
            paradox_s2_opt2: "Der linken Tür vertrauen",
            paradox_s2_opt3: "Der rechten Tür vertrauen",
            paradox_s3_title: "Schrödingers Welle",
            paradox_s3_desc: "Die Katze ist lebendig und tot, bis du die Welle am Peak kollabierst.",
            paradox_s3_hint: "Drücke LEERTASTE genau wenn die Welle gipfelt (█).",
            paradox_s3_peak: "Welle kollabiert! Superposition aufgelöst.",
            paradox_s3_miss: "Falsche Phase. Die Katze ist noch im Fluss.",
            paradox_s4_title: "Das Paradox-Quiz",
            paradox_s4_q0: "Wie viele Fragen hat dieses Quiz?",
            paradox_s4_q0_a0: "Zwei",
            paradox_s4_q0_a1: "Vier",
            paradox_s4_q0_a2: "Drei",
            paradox_s4_q0_a3: "Diese Aussage ist falsch",
            paradox_s4_q1: "Die Antwort auf diese Frage ist:",
            paradox_s4_q1_a0: "Die vorherige Antwort",
            paradox_s4_q1_a1: "Die nächste Antwort",
            paradox_s4_q1_a2: "Zweiundvierzig",
            paradox_s4_q1_a3: "Alle oben genannten",
            paradox_s4_q2: "Wenn du richtig antwortetest, wähle die falsche Option:",
            paradox_s4_q2_a0: "Definitiv diese",
            paradox_s4_q2_a1: "Offensichtlich diese",
            paradox_s4_q2_a2: "Sicherlich diese",
            paradox_s4_q2_a3: "Keine davon (richtig)",
            paradox_s5_title: "Der Umgekehrte Turing-Test",
            paradox_s5_desc: "Beweise, dass du menschlich bist. Löse es vor Ablauf des Timers.",
            paradox_s5_timer: "Zeit",
            paradox_s5_round: "Runde",
            recommender_title: "EMPFEHLUNGEN",
            recommender_subtitle: "Du solltest dir ansehen:",
            recommender_menu_movies: "1. Filme",
            recommender_menu_series: "2. Serien",
            recommender_menu_manga: "3. Manga",
            recommender_menu_books: "4. Bücher",
            recommender_menu_anime: "5. Anime",
            recommender_menu_cartoons: "6. Cartoons",
            recommender_menu_videogames: "7. Videospiele",
            recommender_menu_music: "8. Musik",
            music_menu_title: "MUSIKGENRES",
            music_menu_rock: "1. Rock",
            music_menu_hiphop: "2. Hip-Hop",
            music_menu_pop: "3. Pop",
            music_menu_electronic: "4. Elektronisch",
            music_menu_classical: "5. Klassik",
            music_menu_salsa: "6. Salsa",
            music_menu_reggae: "7. Reggae",
            music_go_back: "8. Zurück (ESC)",
            recommender_go_back: "A. Zurück (ESC)",
            series: super::wordlist::SERIES,
            mangas: super::wordlist::MANGA,
            books: super::wordlist::BOOKS,
            animes: super::wordlist::ANIME,
            cartoons: super::wordlist::CARTOONS,
            videogames: super::wordlist::VIDEO_GAMES,
            
            music_rock: super::wordlist::MUSIC_ROCK,
            music_hiphop: super::wordlist::MUSIC_HIPHOP,
            music_pop: super::wordlist::MUSIC_POP,
            music_electronic: super::wordlist::MUSIC_ELECTRONIC,
            music_classical: super::wordlist::MUSIC_CLASSICAL,
            music_salsa: super::wordlist::MUSIC_SALSA,
            music_reggae: super::wordlist::MUSIC_REGGAE,
            pong_title: "PONG",
            pong_player_wins: "Spieler gewinnt!",
            pong_computer_wins: "Computer gewinnt!",
            pong_instructions: "Auf/Ab zum Bewegen. ESC zurück.",
            menu_go_back: "7. Zurück (ESC)",
            movies: super::wordlist::GERMAN_MOVIES,
        }
    }

    pub fn dutch() -> Self {
        Lang {
            title: "GALGJE",
            prompt_guess: "Voer een letter in (of 'ESC' om te sluiten): ",
            win_msg: "Gefeliciteerd! Je hebt gewonnen!",
            lose_msg: "Spel voorbij! Het woord was: ",
            press_enter: "Druk op Enter om door te gaan...",
            word_label: "Woord: ",
            guessed_label: "Geraden letters: ",
            attempts_label: "Resterende pogingen: ",
            time_left_label: "Resterende tijd: ",
            error_not_letter: "Voer een letter in",
            error_already_guessed: "Je hebt deze letter al geraden",
            menu_game_selection: "Spelselectie",
            menu_hangman: "1. Galgje",
            menu_tictactoe: "2. Boter-kaas-en-eieren",
            menu_chess: "3. Schaken",
            chess_title: "SCHAKEN",
            chess_your_turn: "Jouw beurt",
            chess_white_wins: "Wit wint!",
            chess_black_wins: "Zwart wint!",
            chess_stalemate: "Pat!",
            chess_draw: "Gelijkspel!",
            chess_instructions_ongoing: "Pijltjes voor verplaatsen, Enter voor selecteren. ESC terug.",
            chess_instructions_over: "Druk op Enter om opnieuw te spelen. ESC voor terug.",
            menu_pong: "4. Pong",
            menu_matrix: "5. Matrix",
            menu_paradox: "6. Paradox",
            menu_recommender: "6. Aanbevelingen",
            paradox_title: "PARADOX",
            paradox_stage: "Fase",
            paradox_bypass_hint: "[B] Logica-Bypass",
            paradox_bypass_msg: "Reality.exe gehoorzaamt niet meer. Je hackte de causaliteit met één toets.",
            paradox_complete: "PARADOX OPGELOST",
            paradox_complete_msg: "Je boog de logica tot ze terugveren. Het universum stemt tegen zijn zin in.",
            paradox_esc: "ESC om terug te gaan",
            paradox_s1_title: "De Teleporterende Selector",
            paradox_s1_desc: "Vang de knop tijdens het limoengroene freeze-venster. Buiten dat venster teleporteert het doel weg.",
            paradox_s1_freeze: "FREEZE-VENSTER ACTIEF",
            paradox_s1_hint: "Pijltjes bewegen de cursor. Enter selecteert. Wacht op de limoengloed.",
            paradox_s2_title: "De Poort van de Leugenaar",
            paradox_s2_desc: "Twee wachters blokkeren het pad. Eén liegt altijd, de ander spreekt altijd de waarheid.",
            paradox_s2_alpha: "Alpha: \"Beta is de leugenaar.\"",
            paradox_s2_beta: "Beta: \"We liegen allebei.\"",
            paradox_s2_opt0: "Alpha vragen welke deur veilig is",
            paradox_s2_opt1: "Beta vragen welke deur veilig is",
            paradox_s2_opt2: "De linkerdeur vertrouwen",
            paradox_s2_opt3: "De rechterdeur vertrouwen",
            paradox_s3_title: "Schrödingers Golf",
            paradox_s3_desc: "De kat is levend en dood tot je de golf op haar piek laat instorten.",
            paradox_s3_hint: "Druk SPATIE precies wanneer de golf piekt (█).",
            paradox_s3_peak: "Golf ingestort! Superpositie opgelost.",
            paradox_s3_miss: "Verkeerde fase. De kat is nog in flux.",
            paradox_s4_title: "De Paradox Quiz",
            paradox_s4_q0: "Hoeveel vragen zitten er in deze quiz?",
            paradox_s4_q0_a0: "Twee",
            paradox_s4_q0_a1: "Vier",
            paradox_s4_q0_a2: "Drie",
            paradox_s4_q0_a3: "Deze bewering is onwaar",
            paradox_s4_q1: "Het antwoord op deze vraag is:",
            paradox_s4_q1_a0: "Het vorige antwoord",
            paradox_s4_q1_a1: "Het volgende antwoord",
            paradox_s4_q1_a2: "Tweeënveertig",
            paradox_s4_q1_a3: "Alle bovenstaande",
            paradox_s4_q2: "Als je correct antwoordde, kies de foute optie:",
            paradox_s4_q2_a0: "Zeker deze",
            paradox_s4_q2_a1: "Duidelijk deze",
            paradox_s4_q2_a2: "Absoluut deze",
            paradox_s4_q2_a3: "Geen van deze (correct)",
            paradox_s5_title: "De Omgekeerde Turing-Test",
            paradox_s5_desc: "Bewijs dat je mens bent. Los op voordat de timer afloopt.",
            paradox_s5_timer: "Tijd",
            paradox_s5_round: "Ronde",
            recommender_title: "AANBEVELINGEN",
            recommender_subtitle: "Je zou dit moeten bekijken:",
            recommender_menu_movies: "1. Films",
            recommender_menu_series: "2. Series",
            recommender_menu_manga: "3. Manga",
            recommender_menu_books: "4. Boeken",
            recommender_menu_anime: "5. Anime",
            recommender_menu_cartoons: "6. Tekenfilms",
            recommender_menu_videogames: "7. Videospellen",
            recommender_menu_music: "8. Muziek",
            music_menu_title: "MUZIEKGENRES",
            music_menu_rock: "1. Rock",
            music_menu_hiphop: "2. Hip-Hop",
            music_menu_pop: "3. Pop",
            music_menu_electronic: "4. Elektronisch",
            music_menu_classical: "5. Klassiek",
            music_menu_salsa: "6. Salsa",
            music_menu_reggae: "7. Reggae",
            music_go_back: "8. Ga terug (ESC)",
            recommender_go_back: "A. Ga terug (ESC)",
            series: super::wordlist::SERIES,
            mangas: super::wordlist::MANGA,
            books: super::wordlist::BOOKS,
            animes: super::wordlist::ANIME,
            cartoons: super::wordlist::CARTOONS,
            videogames: super::wordlist::VIDEO_GAMES,
            
            music_rock: super::wordlist::MUSIC_ROCK,
            music_hiphop: super::wordlist::MUSIC_HIPHOP,
            music_pop: super::wordlist::MUSIC_POP,
            music_electronic: super::wordlist::MUSIC_ELECTRONIC,
            music_classical: super::wordlist::MUSIC_CLASSICAL,
            music_salsa: super::wordlist::MUSIC_SALSA,
            music_reggae: super::wordlist::MUSIC_REGGAE,
            pong_title: "PONG",
            pong_player_wins: "Speler wint!",
            pong_computer_wins: "Computer wint!",
            pong_instructions: "Omhoog/Omlaag om te bewegen. ESC terug.",
            menu_go_back: "7. Ga terug (ESC)",
            movies: super::wordlist::DUTCH_MOVIES,
        }
    }

    pub fn from_language(lang: Language) -> Self {
        match lang {
            Language::English => Self::english(),
            Language::Spanish => Self::spanish(),
            Language::Portuguese => Self::portuguese(),
            Language::German => Self::german(),
            Language::Dutch => Self::dutch(),
        }
    }
}
