pub enum Language {
    English,
    Spanish,
    Portuguese,
    German,
    Dutch,
}

#[derive(Clone)]
pub struct Lang {
    pub title: &'static str,
    pub prompt_guess: &'static str,
    pub win_msg: &'static str,
    pub lose_msg: &'static str,
    pub press_enter: &'static str,
    pub word_label: &'static str,
    pub guessed_label: &'static str,
    pub attempts_label: &'static str,
    pub time_left_label: &'static str,
    pub error_not_letter: &'static str,
    pub error_already_guessed: &'static str,
    pub menu_game_selection: &'static str,
    pub menu_hangman: &'static str,
    pub menu_tictactoe: &'static str,
    pub menu_chess: &'static str,
    pub chess_title: &'static str,
    pub chess_your_turn: &'static str,
    pub chess_white_wins: &'static str,
    pub chess_black_wins: &'static str,
    pub chess_stalemate: &'static str,
    pub chess_draw: &'static str,
    pub chess_instructions_ongoing: &'static str,
    pub chess_instructions_over: &'static str,
    pub menu_pong: &'static str,
    pub menu_movie: &'static str,
    pub movie_title: &'static str,
    pub movie_subtitle: &'static str,
    pub pong_title: &'static str,
    pub pong_player_wins: &'static str,
    pub pong_computer_wins: &'static str,
    pub pong_instructions: &'static str,
    pub menu_go_back: &'static str,
    pub movies: &'static [&'static str],
}

impl Lang {
    pub fn english() -> Self {
        Lang {
            title: "HANGMAN",
            prompt_guess: "Enter a letter (or 'ESC' to exit): ",
            win_msg: "Congratulations! You won!",
            lose_msg: "Game over! The word was: ",
            press_enter: "Press Enter to continue...",
            word_label: "Word: ",
            guessed_label: "Guessed letters: ",
            attempts_label: "Attempts left: ",
            time_left_label: "Time left: ",
            error_not_letter: "Please enter a letter",
            error_already_guessed: "You already guessed that letter",
            menu_game_selection: "Game Selection",
            menu_hangman: "1. Hangman",
            menu_tictactoe: "2. Tic-Tac-Toe",
            menu_chess: "3. Chess",
            chess_title: "CHESS",
            chess_your_turn: "Your turn",
            chess_white_wins: "White wins!",
            chess_black_wins: "Black wins!",
            chess_stalemate: "Stalemate!",
            chess_draw: "Draw!",
            chess_instructions_ongoing: "Arrow keys to move, Enter to select/move. ESC to go back.",
            chess_instructions_over: "Press Enter to play again. ESC to go back.",
            menu_pong: "4. Pong",
            menu_movie: "5. Movie Recommender",
            movie_title: "MOVIE RECOMMENDER",
            movie_subtitle: "You should watch:",
            pong_title: "PONG",
            pong_player_wins: "Player wins!",
            pong_computer_wins: "Computer wins!",
            pong_instructions: "Up/Down to move. ESC to go back.",
            menu_go_back: "6. Go Back (ESC)",
            movies: super::wordlist::ENGLISH_MOVIES,
        }
    }

    pub fn spanish() -> Self {
        Lang {
            title: "AHORCADO",
            prompt_guess: "Ingresa una letra (o 'ESC' para salir): ",
            win_msg: "¡Felicidades! ¡Ganaste!",
            lose_msg: "¡Juego terminado! La palabra era: ",
            press_enter: "Presiona Enter para continuar...",
            word_label: "Palabra: ",
            guessed_label: "Letras adivinadas: ",
            attempts_label: "Intentos restantes: ",
            time_left_label: "Tiempo restante: ",
            error_not_letter: "Por favor ingresa una letra",
            error_already_guessed: "Ya adivinaste esa letra",
            menu_game_selection: "Selección de Juego",
            menu_hangman: "1. Ahorcado",
            menu_tictactoe: "2. Tres en Raya",
            menu_chess: "3. Ajedrez",
            chess_title: "AJEDREZ",
            chess_your_turn: "Tu turno",
            chess_white_wins: "¡Las blancas ganan!",
            chess_black_wins: "¡Las negras ganan!",
            chess_stalemate: "¡Rey ahogado!",
            chess_draw: "¡Empate!",
            chess_instructions_ongoing: "Flechas para mover, Enter para seleccionar/mover. ESC para volver.",
            chess_instructions_over: "Presiona Enter para jugar de nuevo. ESC para volver.",
            menu_pong: "4. Pong",
            menu_movie: "5. Movie Recommender",
            movie_title: "MOVIE RECOMMENDER",
            movie_subtitle: "You should watch:",
            pong_title: "PONG",
            pong_player_wins: "¡El jugador gana!",
            pong_computer_wins: "¡La computadora gana!",
            pong_instructions: "Arriba/Abajo para mover. ESC para volver.",
            menu_go_back: "6. Volver (ESC)",
            movies: super::wordlist::SPANISH_MOVIES,
        }
    }

    pub fn portuguese() -> Self {
        Lang {
            title: "FORCA",
            prompt_guess: "Digite uma letra (ou 'ESC' para sair): ",
            win_msg: "Parabéns! Você ganhou!",
            lose_msg: "Fim de jogo! A palavra era: ",
            press_enter: "Pressione Enter para continuar...",
            word_label: "Palavra: ",
            guessed_label: "Letras adivinhadas: ",
            attempts_label: "Tentativas restantes: ",
            time_left_label: "Tempo restante: ",
            error_not_letter: "Por favor, digite uma letra",
            error_already_guessed: "Você já adivinhou essa letra",
            menu_game_selection: "Seleção de Jogo",
            menu_hangman: "1. Forca",
            menu_tictactoe: "2. Jogo da Velha",
            menu_chess: "3. Xadrez",
            chess_title: "XADREZ",
            chess_your_turn: "Sua vez",
            chess_white_wins: "As brancas vencem!",
            chess_black_wins: "As pretas vencem!",
            chess_stalemate: "Afogamento!",
            chess_draw: "Empate!",
            chess_instructions_ongoing: "Setas para mover, Enter para selecionar/mover. ESC para voltar.",
            chess_instructions_over: "Pressione Enter para jogar novamente. ESC para voltar.",
            menu_pong: "4. Pong",
            menu_movie: "5. Movie Recommender",
            movie_title: "MOVIE RECOMMENDER",
            movie_subtitle: "You should watch:",
            pong_title: "PONG",
            pong_player_wins: "O jogador vence!",
            pong_computer_wins: "O computador vence!",
            pong_instructions: "Cima/Baixo para mover. ESC para voltar.",
            menu_go_back: "6. Voltar (ESC)",
            movies: super::wordlist::PORTUGUESE_MOVIES,
        }
    }

    pub fn german() -> Self {
        Lang {
            title: "GALGENMÄNNCHEN",
            prompt_guess: "Buchstabe eingeben (oder 'ESC' zum Beenden): ",
            win_msg: "Herzlichen Glückwunsch! Du hast gewonnen!",
            lose_msg: "Spiel vorbei! Das Wort war: ",
            press_enter: "Drücke Enter, um fortzufahren...",
            word_label: "Wort: ",
            guessed_label: "Geratene Buchstaben: ",
            attempts_label: "Verbleibende Versuche: ",
            time_left_label: "Verbleibende Zeit: ",
            error_not_letter: "Bitte gib einen Buchstaben ein",
            error_already_guessed: "Du hast diesen Buchstaben bereits geraten",
            menu_game_selection: "Spielauswahl",
            menu_hangman: "1. Galgenmännchen",
            menu_tictactoe: "2. Tic-Tac-Toe",
            menu_chess: "3. Schach",
            chess_title: "SCHACH",
            chess_your_turn: "Du bist dran",
            chess_white_wins: "Weiß gewinnt!",
            chess_black_wins: "Schwarz gewinnt!",
            chess_stalemate: "Patt!",
            chess_draw: "Unentschieden!",
            chess_instructions_ongoing: "Pfeiltasten zum Bewegen, Enter zum Auswählen/Ziehen. ESC zurück.",
            chess_instructions_over: "Enter drücken für ein neues Spiel. ESC zum Zurückgehen.",
            menu_pong: "4. Pong",
            menu_movie: "5. Movie Recommender",
            movie_title: "MOVIE RECOMMENDER",
            movie_subtitle: "You should watch:",
            pong_title: "PONG",
            pong_player_wins: "Spieler gewinnt!",
            pong_computer_wins: "Computer gewinnt!",
            pong_instructions: "Auf/Ab zum Bewegen. ESC zurück.",
            menu_go_back: "6. Zurück (ESC)",
            movies: super::wordlist::GERMAN_MOVIES,
        }
    }

    pub fn dutch() -> Self {
        Lang {
            title: "GALGJE",
            prompt_guess: "Voer een letter in (of 'ESC' om te sluiten): ",
            win_msg: "Gefeliciteerd! Je hebt gewonnen!",
            lose_msg: "Spel voorbij! Het woord was: ",
            press_enter: "Druk op Enter om door te gaan...",
            word_label: "Woord: ",
            guessed_label: "Geraden letters: ",
            attempts_label: "Resterende pogingen: ",
            time_left_label: "Resterende tijd: ",
            error_not_letter: "Voer een letter in",
            error_already_guessed: "Je hebt deze letter al geraden",
            menu_game_selection: "Spelselectie",
            menu_hangman: "1. Galgje",
            menu_tictactoe: "2. Boter-kaas-en-eieren",
            menu_chess: "3. Schaken",
            chess_title: "SCHAKEN",
            chess_your_turn: "Jouw beurt",
            chess_white_wins: "Wit wint!",
            chess_black_wins: "Zwart wint!",
            chess_stalemate: "Pat!",
            chess_draw: "Gelijkspel!",
            chess_instructions_ongoing: "Pijltjes voor verplaatsen, Enter voor selecteren. ESC terug.",
            chess_instructions_over: "Druk op Enter om opnieuw te spelen. ESC voor terug.",
            menu_pong: "4. Pong",
            menu_movie: "5. Movie Recommender",
            movie_title: "MOVIE RECOMMENDER",
            movie_subtitle: "You should watch:",
            pong_title: "PONG",
            pong_player_wins: "Speler wint!",
            pong_computer_wins: "Computer wint!",
            pong_instructions: "Omhoog/Omlaag om te bewegen. ESC terug.",
            menu_go_back: "6. Ga terug (ESC)",
            movies: super::wordlist::DUTCH_MOVIES,
        }
    }

    pub fn from_language(lang: Language) -> Self {
        match lang {
            Language::English => Self::english(),
            Language::Spanish => Self::spanish(),
            Language::Portuguese => Self::portuguese(),
            Language::German => Self::german(),
            Language::Dutch => Self::dutch(),
        }
    }
}
