pub const ENGLISH_MOVIES: &[&str] = &[
    "The Godfather",
    "The Shawshank Redemption",
    "The Dark Knight",
    "Pulp Fiction",
    "Forrest Gump",
    "Inception",
    "The Matrix",
    "Interstellar",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Two Towers",
    "The Lord of the Rings: The Return of the King",
    "Fight Club",
    "Star Wars: Episode IV - A New Hope",
    "Star Wars: Episode V - The Empire Strikes Back",
    "Star Wars: Episode VI - Return of the Jedi",
    "The Silence of the Lambs",
    "Saving Private Ryan",
    "The Green Mile",
    "Schindler's List",
    "The Departed",
    "The Prestige",
    "Gladiator",
    "The Lion King",
    "Titanic",
    "Avatar",
    "Jurassic Park",
    "The Terminator",
    "Terminator 2: Judgment Day",
    "Alien",
    "Aliens",
    "Blade Runner",
    "Blade Runner 2049",
    "Back to the Future",
    "The Wizard of Oz",
    "Casablanca",
    "Citizen Kane",
    "Psycho",
    "2001: A Space Odyssey",
    "Vertigo",
    "North by Northwest",
    "The Bridge on the River Kwai",
    "Lawrence of Arabia",
    "Ben-Hur",
    "The Sound of Music",
    "West Side Story",
    "My Fair Lady",
    "The Apartment",
    "Some Like It Hot",
    "All About Eve",
    "Sunset Boulevard",
    "The Maltese Falcon",
    "It's a Wonderful Life",
    "Singin' in the Rain",
    "Annie Hall",
    "Rocky",
    "Platoon",
    "Goodfellas",
    "The Usual Goodfellas",
    "The Usual Suspects",
    "Se7en",
    "City of God",
    "Spirited Away",
    "Parasite",
    "Whiplash",
    "The Intouchables",
    "The Pianist",
    "The Truman Show",
    "Grave of the Fireflies",
    "Modern Times",
    "Rear Window",
    "Raiders of the Lost Ark",
    "Indiana Jones and the Last Crusade",
    "Apocalypse Now",
    "Memento",
    "Django Unchained",
    "WALL-E",
    "Spider-Man: Into the Spider-Verse",
    "Avengers: Infinity War",
    "Avengers: Endgame",
    "Joker",
    "Braveheart",
    "Toy Story",
    "Toy Story 3",
    "Up",
    "Inside Out",
    "Coco",
    "Ratatouille",
    "The Shining",
    "A Clockwork Orange",
    "Full Metal Jacket",
    "Taxi Driver",
    "Good Will Hunting",
    "Scarface",
    "Raging Bull",
    "Chinatown",
    "Amadeus",
    "Fargo",
    "No Country for Old Men",
    "The Big Lebowski",
    "There Will Be Blood",
    "Mad Max: Fury Road",
    "Inglourious Basterds",
    "Kill Bill: Vol. 1",
    "Reservoir Dogs",
];

pub const SPANISH_MOVIES: &[&str] = &[
    "El Padrino",
    "Cadena perpetua",
    "El caballero oscuro",
    "Pulp Fiction",
    "Forrest Gump",
    "Inception",
    "Matrix",
    "Interstellar",
    "El señor de los anillos: La comunidad del anillo",
    "El club de la pelea",
    "Star Wars: Episode V - El imperio contraataca",
    "El silencio de los corderos",
    "Salvar al soldado Ryan",
    "La milla verde",
    "La lista de Schindler",
    "Los infiltrados",
    "El prestigio",
    "Gladiator",
    "El rey león",
    "Titanic",
    "Avatar",
    "Parque Jurásico",
    "Terminator",
    "Alien",
    "Blade Runner",
    "Volver al futuro",
    "El mago de Oz",
    "Casablanca",
    "Citizen Kane",
    "Psicosis",
    "2001: Una odisea del espacio",
    "Vértigo",
    "Con la muerte en los talones",
    "El puente sobre el río Kwai",
    "Lawrence de Arabia",
    "Ben-Hur",
    "Sonrisas y lágrimas",
    "West Side Story",
    "My Fair Lady",
    "El apartamento",
    "Some Like It Hot",
    "Todo sobre Eva",
    "El crepúsculo del gods",
    "El halcón maltés",
    "Es una vida maravillosa",
    "Cantando bajo la lluvia",
    "Annie Hall",
    "Rocky",
    "Platoon",
    "El laberinto del fauno",
    "Volver",
    "Todo sobre mi madre",
    "Amores perros",
    "Y tu mamá también",
    "El espinazo del diablo",
    "Los olvidados",
    "Roma",
    "El angel exterminador",
    "Santa Sangre",
    "La vida es sueño",
    "El norte",
    "Como agua para chocolate",
    "Pan's Labyrinth",
    "El orfanato",
    "También la lluvia",
    "El buen patrón",
    "Madres paralelas",
    "El interior de la noche",
];

pub const PORTUGUESE_MOVIES: &[&str] = &[
    "O Poderoso Chefão",
    "Um Sonho de Liberdade",
    "O Cavaleiro das Trevas",
    "Pulp Fiction",
    "Forrest Gump",
    "A Origem",
    "Matrix",
    "Interestelar",
    "O Senhor dos Anéis: A Sociedade do Anel",
    "Clube da Luta",
    "Star Wars: Episódio V - O Império Contra-Ataca",
    "O Silêncio dos Inocentes",
    "Salvando o Soldado Ryan",
    "A Verde Milha",
    "A Lista de Schindler",
    "Os Infiltrados",
    "O Prestígiado",
    "Gladiador",
    "O Rei Leão",
    "Titanic",
    "Avatar",
    "Parque Jurássico",
    "O Exterminador do Futuro",
    "Alien",
    "Blade Runner",
    "De Volta para o Futuro",
    "O Mágico de Oz",
    "Casablanca",
    "Cidadão Kane",
    "Psicose",
    "2001: Uma Odisseia no Espaço",
    "Vertigem",
    "A Janela Indiscreta",
    "A Ponte do Rio Kwai",
    "Lawrence da Arábia",
    "Ben-Hur",
    "Todo em乐 sobre Eva",
    "Cantando na Chuva",
    "Annie Hall",
    "Rocky",
    "Platoon",
    "O Labirinto do Fauno",
    "Volver",
    "Todo sobre a Minha Mãe",
    "Amores Perros",
    "E Também a Chuva",
    "O Bom Patrão",
    "Mães Paralelas",
    "O Interior da Noite",
];

pub const GERMAN_MOVIES: &[&str] = &[
    "Der Pate",
    "Die Verurteilten",
    "Der Dunkle Ritter",
    "Pulp Fiction",
    "Forrest Gump",
    "Inception",
    "Matrix",
    "Interstellar",
    "Fight Club",
    "Das Schweigen der Lämmer",
    "Der Soldat James Ryan",
    "The Green Mile",
    "Schindlers Liste",
    "Departed",
    "Prestige",
];

pub const DUTCH_MOVIES: &[&str] = &[
    "De Peetvader",
    "De Veroordeelden",
    "De Donkere Ridder",
    "Pulp Fiction",
    "Forrest Gump",
    "Inception",
    "Matrix",
    "Interstellar",
    "Fight Club",
    "De Stilte van de Lammeren",
    "Saving Private Ryan",
    "The Green Mile",
    "Schindlers List",
    "The Departed",
    "The Prestige",
];

pub const SERIES: &[&str] = &[
    "Breaking Bad",
    "The Wire",
    "Game of Thrones",
    "The Sopranos",
    "Stranger Things",
    "The Office",
    "Avatar: The Last Airbender",
    "Sherlock",
    "True Detective",
    "Fargo",
    "Better Call Saul",
    "Succession",
    "Chernobyl",
    "Mad Men",
    "The Twilight Zone",
    "Band of Brothers",
    "Black Mirror",
    "Peaky Blinders",
    "Mr. Robot",
    "The Crown",
    "Dark",
    "Fleabag",
    "House of Cards",
    "Mindhunter",
    "The Boys",
    "Severance",
    "The Mandalorian",
    "Narcos",
    "The Last of Us",
    "Arcane",
    "Boardwalk Empire",
    "The Leftovers",
    "Atlanta",
    "Barry",
    "BoJack Horseman",
    "The Shield",
    "Six Feet Under",
    "Twin Peaks",
    "Deadwood",
    "Seinfeld",
    "Curb Your Enthusiasm",
    "It's Always Sunny in Philadelphia",
    "Arrested Development",
    "The Simpsons",
    "Friends",
    "South Park",
    "Rick and Morty",
    "The X-Files",
    "Dexter",
    "Hannibal",
    "Mindhunter",
    "Ozark",
    "The Americans",
    "The Expanse",
    "Westworld",
    "Battlestar Galactica",
    "Doctor Who",
    "Firefly",
    "Lost",
    "Fringe",
    "Prison Break",
    "Homeland",
    "Justified",
    "Sons of Anarchy",
    "Yellowstone",
    "Snowfall",
    "Billions",
    "Line of Duty",
    "Broadchurch",
    "Happy Valley",
    "Luther",
    "The Fall",
    "Bodyguard",
    "Mare of Easttown",
    "Killing Eve",
    "The Night Of",
    "True Blood",
    "Rome",
    "Carnivàle",
    "Treme",
    "The Knick",
    "Generation Kill",
    "Show Me a Hero",
    "The Deuce",
    "Vinyl",
    "The Newsroom",
    "In Treatment",
    "Getting On",
    "Enlightened",
    "Big Love",
    "Six Feet Under",
    "Oz",
    "The Corner",
    "John from Cincinnati",
    "The Plot Against America",
    "We Own This City",
    "The Wire",
    "Homicide: Life on the Street",
    "The Corner",
];

pub const MANGA: &[&str] = &[
    "Berserk",
    "Monster",
    "One Piece",
    "Fullmetal Alchemist",
    "Oyasumi Punpun",
    "Vagabond",
    "Death Note",
    "Hunter x Hunter",
    "Attack on Titan",
    "Naruto",
    "Bleach",
    "Vinland Saga",
    "JoJo's Bizarre Adventure",
    "Tokyo Ghoul",
    "Chainsaw Man",
    "Demon Slayer",
    "Jujutsu Kaisen",
    "Akira",
    "Dragon Ball",
    "Slam Dunk",
    "20th Century Boys",
    "Kingdom",
    "Neon Genesis Evangelion",
    "Spy x Family",
    "Haikyuu!!",
    "My Hero Academia",
    "Gantz",
    "Nana",
    "Kaguya-sama: Love is War",
    "Blue Lock",
    "Goodnight Punpun",
    "Yotsuba to!",
    "Pluto",
    "Real",
    "Billy Bat",
    "Master Keaton",
    "Maison Ikkoku",
    "Cross Game",
    "Real",
    "Dorohedoro",
    "Blame!",
    "Dai Dark",
    "Golden Kamuy",
    "Planetes",
    "Knights of Sidonia",
    "Biomega",
    "Aposimz",
    "Gintama",
    "Grand Blue",
    "Cross Game",
    "Touch",
    "H2",
    "Rough",
    "Katsu!",
    "Mix",
    "Yawara!",
    "Ranma 1/2",
    "Urusei Yatsura",
    "InuYasha",
    "Kyo Kara Ore Wa!!",
    "Ashita no Joe",
    "Buzzer Beater",
    "Slam Dunk",
    "Vagabond",
    "Real",
    "Ping Pong",
    "Taiyou no Matsumoto",
    "Tekkonkinkreet",
    "Gogo Monster",
    "Number 5",
    "Sunny",
    "Blue Spring",
    "Tokyo Boys & Girls",
    "Takemitsu Zamurai",
    "No. 5",
    "Baki the Grappler",
    "Baki",
    "Baki Hanma",
    "Baki Dou",
    "Garouden",
    "Shamo",
    "Tough",
    "Kengan Ashura",
    "Record of Ragnarok",
    "Hajime no Ippo",
    "Ashita no Joe",
    "Megalo Box",
    "Kaze no Tani no Nausicaa",
    "Ghost in the Shell",
    "Appleseed",
    "Dominion",
    "Orion",
    "Black Magic",
    "Koukaku Kidoutai",
    "Mushishi",
    "Yokohama Kaidashi Kikou",
    "Aria",
    "Aqua",
    "Yotsuba&!",
];

pub const BOOKS: &[&str] = &[
    "1984",
    "To Kill a Mockingbird",
    "The Lord of the Rings",
    "Pride and Prejudice",
    "The Great Gatsby",
    "Moby-Dick",
    "Crime and Punishment",
    "The Catcher in the Rye",
    "Brave New World",
    "The Hobbit",
    "Fahrenheit 451",
    "Jane Eyre",
    "Animal Farm",
    "The Brothers Karamazov",
    "War and Peace",
    "The Odyssey",
    "Frankenstein",
    "Dracula",
    "The Picture of Dorian Gray",
    "A Tale of Two Cities",
    "The Count of Monte Cristo",
    "Les Misérables",
    "Don Quixote",
    "The Alchemist",
    "Dune",
    "Neuromancer",
    "Catch-22",
    "Slaughterhouse-Five",
    "The Hitchhiker's Guide to the Galaxy",
    "Wuthering Heights",
    "The Grapes of Wrath",
    "One Hundred Years of Solitude",
    "The Sound and the Fury",
    "Lolita",
    "Heart of Darkness",
    "Invisible Man",
    "The Trial",
    "The Magic Mountain",
    "Ulysses",
    "In Search of Lost Time",
    "Madame Bovary",
    "The Divine Comedy",
    "The Iliad",
    "The Aeneid",
    "Gilgamesh",
    "Beowulf",
    "The Canterbury Tales",
    "Gulliver's Travels",
    "Alice's Adventures in Wonderland",
    "Robinson Crusoe",
    "Treasure Island",
    "The Adventures of Huckleberry Finn",
    "The Adventures of Tom Sawyer",
    "Little Women",
    "Great Expectations",
    "Oliver Twist",
    "David Copperfield",
    "A Christmas Carol",
    "The Old Man and the Sea",
    "Of Mice and Men",
    "For Whom the Bell Tolls",
    "The Sun Also Rises",
    "A Farewell to Arms",
    "The Metamorphosis",
    "The Stranger",
    "The Castle",
    "Anna Karenina",
    "Fathers and Sons",
    "Dead Souls",
    "The Master and Margarita",
    "The Idiot",
    "Demons",
    "Notes from Underground",
    "Blood Meridian",
    "The Road",
    "No Country for Old Men",
    "All the Pretty Horses",
    "Suttree",
    "The Crossing",
    "Cities of the Plain",
    "Beloved",
    "Song of Solomon",
    "The Bluest Eye",
    "Sula",
    "Midnight's Children",
    "Gravity's Rainbow",
    "Cat's Cradle",
    "Mother Night",
    "The Sirens of Titan",
    "Breakfast of Champions",
    "Player Piano",
    "God Bless You, Mr. Rosewater",
    "Deadeye Dick",
    "Galápagos",
    "Bluebeard",
    "Timequake",
    "Hocus Pocus",
    "Jailbird",
    "Slapstick",
];

pub const ANIME: &[&str] = &[
    "Fullmetal Alchemist: Brotherhood",
    "Steins;Gate",
    "Cowboy Bebop",
    "Neon Genesis Evangelion",
    "Death Note",
    "Hunter x Hunter",
    "Attack on Titan",
    "One Punch Man",
    "Mob Psycho 100",
    "Spirited Away",
    "Princess Mononoke",
    "Your Name",
    "Akira",
    "Ghost in the Shell",
    "Samurai Champloo",
    "Code Geass",
    "Violet Evergarden",
    "Clannad",
    "Demon Slayer",
    "Jujutsu Kaisen",
    "My Hero Academia",
    "Vinland Saga",
    "Naruto",
    "Bleach",
    "One Piece",
    "Cyberpunk: Edgerunners",
    "Gintama",
    "Frieren: Beyond Journey's End",
    "A Silent Voice",
    "Howl's Moving Castle",
    "Nausicaä of the Valley of the Wind",
    "Castle in the Sky",
    "My Neighbor Totoro",
    "Kiki's Delivery Service",
    "Porco Rosso",
    "Whisper of the Heart",
    "The Wind Rises",
    "Grave of the Fireflies",
    "The Tale of the Princess Kaguya",
    "Pom Poko",
    "Only Yesterday",
    "My Neighbors the Yamadas",
    "Ponyo",
    "The Secret World of Arrietty",
    "From Up on Poppy Hill",
    "When Marnie Was There",
    "The Boy and the Heron",
    "Perfect Blue",
    "Paprika",
    "Millennium Actress",
    "Tokyo Godfathers",
    "Paranoia Agent",
    "Memories",
    "Redline",
    "Vampire Hunter D: Bloodlust",
    "Ninja Scroll",
    "Wicked City",
    "Macross Plus",
    "Macross: Do You Remember Love?",
    "Gunbuster",
    "Jin-Roh: The Wolf Brigade",
    "Royal Space Force: The Wings of Honneamise",
    "Angel's Egg",
    "Neo Tokyo",
    "Robot Carnival",
    "Mind Game",
    "Texhnolyze",
    "Dead Leaves",
    "Kaiba",
    "The Tatami Galaxy",
    "Ping Pong the Animation",
    "Devilman Crybaby",
    "Kemonozume",
    "Space Dandy",
    "Michiko & Hatchin",
    "FLCL",
    "Carole & Tuesday",
    "Kids on the Slope",
    "Lu Over the Wall",
    "Maquia: When the Promised Flower Blooms",
    "Weathering with You",
    "Suzume",
    "The Garden of Words",
    "5 Centimeters per Second",
    "Children Who Chase Lost Voices",
    "The Place Promised in Our Early Days",
    "Voices of a Distant Star",
    "Wolf Children",
    "Your Lie in April",
    "I Want to Eat Your Pancreas",
    "A Whisker Away",
    "Josee, the Tiger and the Fish",
    "Penguin Highway",
    "Mirai",
    "Night Is Short, Walk On Girl",
    "Lu Over the Wall",
    "Ride Your Wave",
    "Inu-Oh",
    "The Deer King",
];
