pub const ENGLISH_MOVIES: &[&str] = &[
    "The Godfather",
    "The Shawshank Redemption",
    "The Dark Knight",
    "Pulp Fiction",
    "Forrest Gump",
    "Inception",
    "The Matrix",
    "Interstellar",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Two Towers",
    "The Lord of the Rings: The Return of the King",
    "Fight Club",
    "Star Wars: Episode IV - A New Hope",
    "Star Wars: Episode V - The Empire Strikes Back",
    "Star Wars: Episode VI - Return of the Jedi",
    "The Silence of the Lambs",
    "Saving Private Ryan",
    "The Green Mile",
    "Schindler's List",
    "The Departed",
    "The Prestige",
    "Gladiator",
    "The Lion King",
    "Titanic",
    "Avatar",
    "Jurassic Park",
    "The Terminator",
    "Terminator 2: Judgment Day",
    "Alien",
    "Aliens",
    "Blade Runner",
    "Blade Runner 2049",
    "Back to the Future",
    "The Wizard of Oz",
    "Casablanca",
    "Citizen Kane",
    "Psycho",
    "2001: A Space Odyssey",
    "Vertigo",
    "North by Northwest",
    "The Bridge on the River Kwai",
    "Lawrence of Arabia",
    "Ben-Hur",
    "The Sound of Music",
    "West Side Story",
    "My Fair Lady",
    "The Apartment",
    "Some Like It Hot",
    "All About Eve",
    "Sunset Boulevard",
    "The Maltese Falcon",
    "It's a Wonderful Life",
    "Singin' in the Rain",
    "Annie Hall",
    "Rocky",
    "Platoon",
    "Goodfellas",
    "The Usual Goodfellas",
    "The Usual Suspects",
    "Se7en",
    "City of God",
    "Spirited Away",
    "Parasite",
    "Whiplash",
    "The Intouchables",
    "The Pianist",
    "The Truman Show",
    "Grave of the Fireflies",
    "Modern Times",
    "Rear Window",
    "Raiders of the Lost Ark",
    "Indiana Jones and the Last Crusade",
    "Apocalypse Now",
    "Memento",
    "Django Unchained",
    "WALL-E",
    "Spider-Man: Into the Spider-Verse",
    "Avengers: Infinity War",
    "Avengers: Endgame",
    "Joker",
    "Braveheart",
    "Toy Story",
    "Toy Story 3",
    "Up",
    "Inside Out",
    "Coco",
    "Ratatouille",
    "The Shining",
    "A Clockwork Orange",
    "Full Metal Jacket",
    "Taxi Driver",
    "Good Will Hunting",
    "Scarface",
    "Raging Bull",
    "Chinatown",
    "Amadeus",
    "Fargo",
    "No Country for Old Men",
    "The Big Lebowski",
    "There Will Be Blood",
    "Mad Max: Fury Road",
    "Inglourious Basterds",
    "Kill Bill: Vol. 1",
    "Reservoir Dogs",
];

pub const SPANISH_MOVIES: &[&str] = &[
    "El Padrino",
    "Cadena perpetua",
    "El caballero oscuro",
    "Pulp Fiction",
    "Forrest Gump",
    "Inception",
    "Matrix",
    "Interstellar",
    "El señor de los anillos: La comunidad del anillo",
    "El club de la pelea",
    "Star Wars: Episode V - El imperio contraataca",
    "El silencio de los corderos",
    "Salvar al soldado Ryan",
    "La milla verde",
    "La lista de Schindler",
    "Los infiltrados",
    "El prestigio",
    "Gladiator",
    "El rey león",
    "Titanic",
    "Avatar",
    "Parque Jurásico",
    "Terminator",
    "Alien",
    "Blade Runner",
    "Volver al futuro",
    "El mago de Oz",
    "Casablanca",
    "Citizen Kane",
    "Psicosis",
    "2001: Una odisea del espacio",
    "Vértigo",
    "Con la muerte en los talones",
    "El puente sobre el río Kwai",
    "Lawrence de Arabia",
    "Ben-Hur",
    "Sonrisas y lágrimas",
    "West Side Story",
    "My Fair Lady",
    "El apartamento",
    "Some Like It Hot",
    "Todo sobre Eva",
    "El crepúsculo del gods",
    "El halcón maltés",
    "Es una vida maravillosa",
    "Cantando bajo la lluvia",
    "Annie Hall",
    "Rocky",
    "Platoon",
    "El laberinto del fauno",
    "Volver",
    "Todo sobre mi madre",
    "Amores perros",
    "Y tu mamá también",
    "El espinazo del diablo",
    "Los olvidados",
    "Roma",
    "El angel exterminador",
    "Santa Sangre",
    "La vida es sueño",
    "El norte",
    "Como agua para chocolate",
    "Pan's Labyrinth",
    "El orfanato",
    "También la lluvia",
    "El buen patrón",
    "Madres paralelas",
    "El interior de la noche",
];

pub const PORTUGUESE_MOVIES: &[&str] = &[
    "O Poderoso Chefão",
    "Um Sonho de Liberdade",
    "O Cavaleiro das Trevas",
    "Pulp Fiction",
    "Forrest Gump",
    "A Origem",
    "Matrix",
    "Interestelar",
    "O Senhor dos Anéis: A Sociedade do Anel",
    "Clube da Luta",
    "Star Wars: Episódio V - O Império Contra-Ataca",
    "O Silêncio dos Inocentes",
    "Salvando o Soldado Ryan",
    "A Verde Milha",
    "A Lista de Schindler",
    "Os Infiltrados",
    "O Prestígiado",
    "Gladiador",
    "O Rei Leão",
    "Titanic",
    "Avatar",
    "Parque Jurássico",
    "O Exterminador do Futuro",
    "Alien",
    "Blade Runner",
    "De Volta para o Futuro",
    "O Mágico de Oz",
    "Casablanca",
    "Cidadão Kane",
    "Psicose",
    "2001: Uma Odisseia no Espaço",
    "Vertigem",
    "A Janela Indiscreta",
    "A Ponte do Rio Kwai",
    "Lawrence da Arábia",
    "Ben-Hur",
    "Todo em乐 sobre Eva",
    "Cantando na Chuva",
    "Annie Hall",
    "Rocky",
    "Platoon",
    "O Labirinto do Fauno",
    "Volver",
    "Todo sobre a Minha Mãe",
    "Amores Perros",
    "E Também a Chuva",
    "O Bom Patrão",
    "Mães Paralelas",
    "O Interior da Noite",
];

pub const GERMAN_MOVIES: &[&str] = &[
    "Der Pate",
    "Die Verurteilten",
    "Der Dunkle Ritter",
    "Pulp Fiction",
    "Forrest Gump",
    "Inception",
    "Matrix",
    "Interstellar",
    "Fight Club",
    "Das Schweigen der Lämmer",
    "Der Soldat James Ryan",
    "The Green Mile",
    "Schindlers Liste",
    "Departed",
    "Prestige",
];

pub const DUTCH_MOVIES: &[&str] = &[
    "De Peetvader",
    "De Veroordeelden",
    "De Donkere Ridder",
    "Pulp Fiction",
    "Forrest Gump",
    "Inception",
    "Matrix",
    "Interstellar",
    "Fight Club",
    "De Stilte van de Lammeren",
    "Saving Private Ryan",
    "The Green Mile",
    "Schindlers List",
    "The Departed",
    "The Prestige",
];
