pub const ENGLISH_MOVIES: &[&str] = &[
    "The Godfather",
    "The Shawshank Redemption",
    "The Dark Knight",
    "Pulp Fiction",
    "Forrest Gump",
    "Inception",
    "The Matrix",
    "Interstellar",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Two Towers",
    "The Lord of the Rings: The Return of the King",
    "Fight Club",
    "Star Wars: Episode IV - A New Hope",
    "Star Wars: Episode V - The Empire Strikes Back",
    "Star Wars: Episode VI - Return of the Jedi",
    "The Silence of the Lambs",
    "Saving Private Ryan",
    "The Green Mile",
    "Schindler's List",
    "The Departed",
    "The Prestige",
    "Gladiator",
    "The Lion King",
    "Titanic",
    "Avatar",
    "Jurassic Park",
    "The Terminator",
    "Terminator 2: Judgment Day",
    "Alien",
    "Aliens",
    "Blade Runner",
    "Blade Runner 2049",
    "Back to the Future",
    "The Wizard of Oz",
    "Casablanca",
    "Citizen Kane",
    "Psycho",
    "2001: A Space Odyssey",
    "Vertigo",
    "North by Northwest",
    "The Bridge on the River Kwai",
    "Lawrence of Arabia",
    "Ben-Hur",
    "The Sound of Music",
    "West Side Story",
    "My Fair Lady",
    "The Apartment",
    "Some Like It Hot",
    "All About Eve",
    "Sunset Boulevard",
    "The Maltese Falcon",
    "It's a Wonderful Life",
    "Singin' in the Rain",
    "Annie Hall",
    "Rocky",
    "Platoon",
    "Goodfellas",
    "The Usual Goodfellas",
    "The Usual Suspects",
    "Se7en",
    "City of God",
    "Spirited Away",
    "Parasite",
    "Whiplash",
    "The Intouchables",
    "The Pianist",
    "The Truman Show",
    "Grave of the Fireflies",
    "Modern Times",
    "Rear Window",
    "Raiders of the Lost Ark",
    "Indiana Jones and the Last Crusade",
    "Apocalypse Now",
    "Memento",
    "Django Unchained",
    "WALL-E",
    "Spider-Man: Into the Spider-Verse",
    "Avengers: Infinity War",
    "Avengers: Endgame",
    "Joker",
    "Braveheart",
    "Toy Story",
    "Toy Story 3",
    "Up",
    "Inside Out",
    "Coco",
    "Ratatouille",
    "The Shining",
    "A Clockwork Orange",
    "Full Metal Jacket",
    "Taxi Driver",
    "Good Will Hunting",
    "Scarface",
    "Raging Bull",
    "Chinatown",
    "Amadeus",
    "Fargo",
    "No Country for Old Men",
    "The Big Lebowski",
    "There Will Be Blood",
    "Mad Max: Fury Road",
    "Inglourious Basterds",
    "Kill Bill: Vol. 1",
    "Reservoir Dogs",
];

pub const SPANISH_MOVIES: &[&str] = &[
    "El Padrino",
    "Cadena perpetua",
    "El caballero oscuro",
    "Pulp Fiction",
    "Forrest Gump",
    "Inception",
    "Matrix",
    "Interstellar",
    "El señor de los anillos: La comunidad del anillo",
    "El club de la pelea",
    "Star Wars: Episode V - El imperio contraataca",
    "El silencio de los corderos",
    "Salvar al soldado Ryan",
    "La milla verde",
    "La lista de Schindler",
    "Los infiltrados",
    "El prestigio",
    "Gladiator",
    "El rey león",
    "Titanic",
    "Avatar",
    "Parque Jurásico",
    "Terminator",
    "Alien",
    "Blade Runner",
    "Volver al futuro",
    "El mago de Oz",
    "Casablanca",
    "Citizen Kane",
    "Psicosis",
    "2001: Una odisea del espacio",
    "Vértigo",
    "Con la muerte en los talones",
    "El puente sobre el río Kwai",
    "Lawrence de Arabia",
    "Ben-Hur",
    "Sonrisas y lágrimas",
    "West Side Story",
    "My Fair Lady",
    "El apartamento",
    "Some Like It Hot",
    "Todo sobre Eva",
    "El crepúsculo del gods",
    "El halcón maltés",
    "Es una vida maravillosa",
    "Cantando bajo la lluvia",
    "Annie Hall",
    "Rocky",
    "Platoon",
    "El laberinto del fauno",
    "Volver",
    "Todo sobre mi madre",
    "Amores perros",
    "Y tu mamá también",
    "El espinazo del diablo",
    "Los olvidados",
    "Roma",
    "El angel exterminador",
    "Santa Sangre",
    "La vida es sueño",
    "El norte",
    "Como agua para chocolate",
    "Pan's Labyrinth",
    "El orfanato",
    "También la lluvia",
    "El buen patrón",
    "Madres paralelas",
    "El interior de la noche",
];

pub const PORTUGUESE_MOVIES: &[&str] = &[
    "O Poderoso Chefão",
    "Um Sonho de Liberdade",
    "O Cavaleiro das Trevas",
    "Pulp Fiction",
    "Forrest Gump",
    "A Origem",
    "Matrix",
    "Interestelar",
    "O Senhor dos Anéis: A Sociedade do Anel",
    "Clube da Luta",
    "Star Wars: Episódio V - O Império Contra-Ataca",
    "O Silêncio dos Inocentes",
    "Salvando o Soldado Ryan",
    "A Verde Milha",
    "A Lista de Schindler",
    "Os Infiltrados",
    "O Prestígiado",
    "Gladiador",
    "O Rei Leão",
    "Titanic",
    "Avatar",
    "Parque Jurássico",
    "O Exterminador do Futuro",
    "Alien",
    "Blade Runner",
    "De Volta para o Futuro",
    "O Mágico de Oz",
    "Casablanca",
    "Cidadão Kane",
    "Psicose",
    "2001: Uma Odisseia no Espaço",
    "Vertigem",
    "A Janela Indiscreta",
    "A Ponte do Rio Kwai",
    "Lawrence da Arábia",
    "Ben-Hur",
    "Todo em乐 sobre Eva",
    "Cantando na Chuva",
    "Annie Hall",
    "Rocky",
    "Platoon",
    "O Labirinto do Fauno",
    "Volver",
    "Todo sobre a Minha Mãe",
    "Amores Perros",
    "E Também a Chuva",
    "O Bom Patrão",
    "Mães Paralelas",
    "O Interior da Noite",
];

pub const GERMAN_MOVIES: &[&str] = &[
    "Der Pate",
    "Die Verurteilten",
    "Der Dunkle Ritter",
    "Pulp Fiction",
    "Forrest Gump",
    "Inception",
    "Matrix",
    "Interstellar",
    "Fight Club",
    "Das Schweigen der Lämmer",
    "Der Soldat James Ryan",
    "The Green Mile",
    "Schindlers Liste",
    "Departed",
    "Prestige",
];

pub const DUTCH_MOVIES: &[&str] = &[
    "De Peetvader",
    "De Veroordeelden",
    "De Donkere Ridder",
    "Pulp Fiction",
    "Forrest Gump",
    "Inception",
    "Matrix",
    "Interstellar",
    "Fight Club",
    "De Stilte van de Lammeren",
    "Saving Private Ryan",
    "The Green Mile",
    "Schindlers List",
    "The Departed",
    "The Prestige",
];

pub const SERIES: &[&str] = &[
    "Breaking Bad",
    "The Wire",
    "Game of Thrones",
    "The Sopranos",
    "Stranger Things",
    "The Office",
    "Avatar: The Last Airbender",
    "Sherlock",
    "True Detective",
    "Fargo",
    "Better Call Saul",
    "Succession",
    "Chernobyl",
    "Mad Men",
    "The Twilight Zone",
    "Band of Brothers",
    "Black Mirror",
    "Peaky Blinders",
    "Mr. Robot",
    "The Crown",
    "Dark",
    "Fleabag",
    "House of Cards",
    "Mindhunter",
    "The Boys",
    "Severance",
    "The Mandalorian",
    "Narcos",
    "The Last of Us",
    "Arcane",
];

pub const MANGA: &[&str] = &[
    "Berserk",
    "Monster",
    "One Piece",
    "Fullmetal Alchemist",
    "Oyasumi Punpun",
    "Vagabond",
    "Death Note",
    "Hunter x Hunter",
    "Attack on Titan",
    "Naruto",
    "Bleach",
    "Vinland Saga",
    "JoJo's Bizarre Adventure",
    "Tokyo Ghoul",
    "Chainsaw Man",
    "Demon Slayer",
    "Jujutsu Kaisen",
    "Akira",
    "Dragon Ball",
    "Slam Dunk",
    "20th Century Boys",
    "Kingdom",
    "Neon Genesis Evangelion",
    "Spy x Family",
    "Haikyuu!!",
    "My Hero Academia",
    "Gantz",
    "Nana",
    "Kaguya-sama: Love is War",
    "Blue Lock",
];

pub const BOOKS: &[&str] = &[
    "1984",
    "To Kill a Mockingbird",
    "The Lord of the Rings",
    "Pride and Prejudice",
    "The Great Gatsby",
    "Moby-Dick",
    "Crime and Punishment",
    "The Catcher in the Rye",
    "Brave New World",
    "The Hobbit",
    "Fahrenheit 451",
    "Jane Eyre",
    "Animal Farm",
    "The Brothers Karamazov",
    "War and Peace",
    "The Odyssey",
    "Frankenstein",
    "Dracula",
    "The Picture of Dorian Gray",
    "A Tale of Two Cities",
    "The Count of Monte Cristo",
    "Les Misérables",
    "Don Quixote",
    "The Alchemist",
    "Dune",
    "Neuromancer",
    "Catch-22",
    "Slaughterhouse-Five",
    "The Hitchhiker's Guide to the Galaxy",
    "Wuthering Heights",
];

pub const ANIME: &[&str] = &[
    "Fullmetal Alchemist: Brotherhood",
    "Steins;Gate",
    "Cowboy Bebop",
    "Neon Genesis Evangelion",
    "Death Note",
    "Hunter x Hunter",
    "Attack on Titan",
    "One Punch Man",
    "Mob Psycho 100",
    "Spirited Away",
    "Princess Mononoke",
    "Your Name",
    "Akira",
    "Ghost in the Shell",
    "Samurai Champloo",
    "Code Geass",
    "Violet Evergarden",
    "Clannad",
    "Demon Slayer",
    "Jujutsu Kaisen",
    "My Hero Academia",
    "Vinland Saga",
    "Naruto",
    "Bleach",
    "One Piece",
    "Cyberpunk: Edgerunners",
    "Gintama",
    "Frieren: Beyond Journey's End",
    "A Silent Voice",
    "Howl's Moving Castle",
];
